
CREATE TABLE "WellProductionAggr" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Api" text NOT NULL,
	"Date" timestamp NOT NULL,
	"GAS_VOL" float4 NULL,
	"COND_VOL" float4 NULL,
	"OIL_VOL" float4 NULL,
	CONSTRAINT "WellProductionAggr_pkey" PRIMARY KEY ("Id", "Api", "Date")
)
PARTITION BY HASH ("Api", "Date");

CREATE UNIQUE INDEX CONCURRENTLY "IX_WellProductionAggr" ON ONLY "WellProductionAggr" USING btree ("Api", "Date");

CREATE TABLE "WellProductionAggr_1" PARTITION OF "WellProductionAggr" FOR VALUES WITH (modulus 4, remainder 0);
CREATE TABLE "WellProductionAggr_2" PARTITION OF "WellProductionAggr" FOR VALUES WITH (modulus 4, remainder 1);
CREATE TABLE "WellProductionAggr_3" PARTITION OF "WellProductionAggr" FOR VALUES WITH (modulus 4, remainder 2);
CREATE TABLE "WellProductionAggr_4" PARTITION OF "WellProductionAggr" FOR VALUES WITH (modulus 4, remainder 3);


CREATE UNIQUE INDEX "OgLeaseCycleData_6_pkey" ON public."OgLeaseCycleData_6" USING btree ("Id", )

CREATE UNIQUE INDEX CONCURRENTLY "IX_WellProductionAggr_1" ON ONLY "WellProductionAggr" USING btree ("Api", "Date");
CREATE UNIQUE INDEX CONCURRENTLY "IX_WellProductionAggr_2" ON ONLY "WellProductionAggr" USING btree ("Api", "Date");
CREATE UNIQUE INDEX CONCURRENTLY "IX_WellProductionAggr_3" ON ONLY "WellProductionAggr" USING btree ("Api", "Date");
CREATE UNIQUE INDEX CONCURRENTLY "IX_WellProductionAggr_4" ON ONLY "WellProductionAggr" USING btree ("Api", "Date");


CREATE INDEX CONCURRENTLY "OgLeaseCycleData_OIL_GAS_CODE_DISTRICT_NO_LEASE_NO_idx" ON "OgLeaseCycleData" USING btree ("OIL_GAS_CODE", "DISTRICT_NO", "LEASE_NO")

REINDEX VERBOSE TABLE CONCURRENTLY "OgLeaseCycleData"