//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilGas.Data.RRC.Texas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OilGas.Data.RRC.Texas.Queries.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH AggrRecord AS (
        ///    SELECT &quot;Api&quot;, &quot;DISTRICT_NO&quot;,&quot;LEASE_NO&quot;,&quot;WELL_NO&quot;,&quot;FIELD_CLASS&quot;
        ///    FROM &quot;ProductionAggr&quot;
        ///), GasRecord AS (
        ///    SELECT
        ///        &quot;GasWellRootSegment&quot;.&quot;WL_GAS_OR_OIL&quot;,
        ///        &quot;GasWellRootSegment&quot;.&quot;WL_GAS_NUMERIC_DISTRICT&quot;,
        ///        &quot;GasWellRootSegment&quot;.&quot;WL_GAS_RRC_ID&quot;,
        ///        &quot;GasWellRootSegment&quot;.&quot;WL_GAS_WELL_NUMBER&quot;,
        ///        &quot;GasFormG1Segment&quot;.&quot;WL_GAS_G1_POTENTIAL&quot;,
        ///        &quot;GasFormG1Segment&quot;.&quot;WL_GAS_G1_SLOPE&quot;,
        ///        &quot;GasFormG1Segment&quot;.&quot;WL_GAS_G1_SIWH&quot;,
        ///        &quot;GasFormG [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuildLeaseTestAggr {
            get {
                return ResourceManager.GetString("BuildLeaseTestAggr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH AggrRecord AS (
        ///    SELECT &quot;Api&quot;, &quot;DISTRICT_NO&quot;,&quot;LEASE_NO&quot;,&quot;WELL_NO&quot;
        ///    FROM &quot;ProductionAggr&quot;
        ///), GasRecord AS (
        ///    SELECT
        ///        &quot;GasWellRootSegment&quot;.&quot;WL_GAS_OR_OIL&quot; AS &quot;FIELD_CLASS&quot;,
        ///        &quot;GasWellRootSegment&quot;.&quot;WL_GAS_NUMERIC_DISTRICT&quot; AS &quot;DISTRICT_NUMBER&quot;,
        ///        &quot;GasWellRootSegment&quot;.&quot;WL_GAS_RRC_ID&quot; AS &quot;LEASE_NUMBER&quot;,
        ///        &quot;GasWellRootSegment&quot;.&quot;WL_GAS_WELL_NUMBER&quot; AS &quot;WELL_NUMBER&quot;,
        ///        COALESCE(&quot;GasFormG1Segment&quot;.&quot;WL_GAS_G1_SIWH&quot;, &quot;GasFormG10Segment&quot;.&quot;WL_G10_SIWH&quot;) AS &quot;SIWH&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuildLeaseWellTestAggr {
            get {
                return ResourceManager.GetString("BuildLeaseWellTestAggr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    &quot;GasWellRootSegment&quot;.&quot;WL_GAS_OR_OIL&quot; AS &quot;FIELD_CLASS&quot;,
        ///    &quot;GasWellRootSegment&quot;.&quot;WL_GAS_NUMERIC_DISTRICT&quot; AS &quot;DISTRICT_NUMBER&quot;,
        ///    &quot;GasWellRootSegment&quot;.&quot;WL_GAS_RRC_ID&quot; AS &quot;LEASE_NUMBER&quot;,
        ///    &quot;GasWellRootSegment&quot;.&quot;WL_GAS_WELL_NUMBER&quot; AS &quot;WELL_NUMBER&quot;,
        ///    COALESCE(&quot;GasFormG1Segment&quot;.&quot;WL_GAS_G1_SIWH&quot;, &quot;GasFormG10Segment&quot;.&quot;WL_G10_SIWH&quot;) AS &quot;SIWH&quot;,
        ///    COALESCE(&quot;GasFormG1Segment&quot;.&quot;WL_GAS_G1_BHP&quot;, &quot;GasFormG10Segment&quot;.&quot;WL_G10_BHP&quot;) AS &quot;AVG_RESERVOIR_BHP&quot;,
        ///    COALESCE(&quot;GasFormG1Segment&quot;.&quot;WL_GAS_G1_GAS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GasWellRootQuery {
            get {
                return ResourceManager.GetString("GasWellRootQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    &quot;WellTestAggr&quot;.&quot;FL_DISTRICT&quot; AS &quot;DISTRICT_NUMBER&quot;,
        ///    &quot;WellTestAggr&quot;.&quot;FL_RESERVOIR_NUMBER&quot; AS &quot;RESERVOIR_NUMBER&quot;,
        ///    &quot;WellTestAggr&quot;.&quot;FL_FIELD_CLASS&quot; AS &quot;FIELD_CLASS&quot;,
        ///    &quot;WellTestAggr&quot;.&quot;FL_RESERVOIR_NAME&quot; AS &quot;RESERVOIR_NAME&quot;,
        ///    &quot;WellTestAggr&quot;.&quot;FL_OIL_DISC_WELL_GRAVITY&quot; AS &quot;OIL_GRAVITY&quot;,
        ///    &quot;WellTestAggr&quot;.&quot;FL_RRCID_DETERMINING_WELL&quot; AS &quot;LEASE_NUMBER&quot;,
        ///    &quot;WellTestAggr&quot;.&quot;FL_G_1_GAS_GRAVITY&quot; AS &quot;GAS_GRAVITY&quot;,
        ///    &quot;WellTestAggr&quot;.&quot;FL_AVG_RESERVOIR_BHP&quot; AS &quot;AVG_RESERVOIR_BHP&quot;,
        ///    &quot;WellTestAggr&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OilWellRootQuery {
            get {
                return ResourceManager.GetString("OilWellRootQuery", resourceCulture);
            }
        }
    }
}
